apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXOWhZV0ppT2xsVmJXRmtZbkp2TWpNMCIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson